#!/bin/bash
###############################################################################
# This script creates all applications and libraries of the CNDF
###############################################################################

ROOTDIR=`pwd`

echo $ROOTDIR

# echo creating Altera applications

# Create single NIOS designs
#----------------------------
./create-this-app --rebuild --no-make -C ${ROOTDIR}/powerlink/EBV_DBC3C40_DigitalIO


# Create dual NIOS designs:
#--------------------------
# PCP Applications:
./create-this-app --rebuild --no-make -C ${ROOTDIR}/powerlink/EBV_DBC3C40_DPRAM

./create-this-app --rebuild --no-make -C ${ROOTDIR}/powerlink/EBV_DBC3C40_DPRAM_PresChain

# AP Applications:
./create-this-app --rebuild --no-make -C ${ROOTDIR}/apps/EBV_DBC3C40_DigitalIO


# Make all
-----------
make -C ${ROOTDIR}/libCnApi/target/nios2_newlib

make -C ${ROOTDIR}/apps/EBV_DBC3C40_DigitalIO

make -C ${ROOTDIR}/powerlink/EBV_DBC3C40_DPRAM

make -C ${ROOTDIR}/powerlink/EBV_DBC3C40_DPRAM_PresChain

exit 0