#!/bin/bash
###############################################################################
# This script creates all applications and libraries of the CNDF
###############################################################################

ROOTDIR=`pwd`

echo $ROOTDIR

# echo creating Altera applications

# Create single NIOS designs
# ----------------------------
cd ${ROOTDIR}/powerlink/EBV_DBC3C40_DigitalIO
./create-this-app --rebuild --no-make
cd ${ROOTDIR}

# Create dual NIOS designs:
# --------------------------
# PCP Applications:
cd ${ROOTDIR}/powerlink/EBV_DBC3C40_DPRAM
./create-this-app --rebuild --no-make
cd ${ROOTDIR}

# AP Applications:
cd ${ROOTDIR}/apps/EBV_DBC3C40_DigitalIO
./create-this-app --rebuild --no-make
cd ${ROOTDIR}


# Make all
# -----------
make -C ${ROOTDIR}/libCnApi/target/nios2_newlib # has to be created first!

make -C ${ROOTDIR}/apps/EBV_DBC3C40_DigitalIO

make -C ${ROOTDIR}/powerlink/EBV_DBC3C40_DPRAM

exit 0