#!/bin/sh
#
# File: post-checkout
# Autor: Thomas Mair
# Date:  10.10.2012
#
# Desc: This hook is called after a successful checkout 
#       and a successful clone.
#       Please set variable PLATFORM to your desired platform
#
# Usage: Pass platform [altera, xilinx] as an argument
#        e.g: ./post-checkout xilinx
#        when no argument is passed the value from $PLATFORM is used
# 

if [ $# -eq 1 ]
then
	# if parameter is passed use the parameter
	PLATFORM=$1
else
	# change this: PLATFORM = [altera, xilinx]
	PLATFORM=altera
fi

# path settings
CNDK_DIR=$PWD

PCP_PDI_DIR=$CNDK_DIR/powerlink/pcp_PDI
PCP_DIRECTIO_DIR=$CNDK_DIR/powerlink/pcp_DirectIO
AP_PDI_DIR=$CNDK_DIR/apps/ap_PDI
LIBCNAPI_DIR=$CNDK_DIR/libCnApi


if [[ $PLATFORM != "altera" ]] && [[ $PLATFORM != "xilinx" ]];
then
	echo "HOOK ERROR: (post-checkout) Invalid platform specified! Set var PLATFORM to altera or xilinx!"
	exit 1
fi

# first clean the project directories (can be dangerous)
#git clean -xdf $PCP_PDI_DIR $PCP_DIRECTIO_DIR $AP_PDI_DIR

# do checkout for desired platform
echo "INFO: (post-checkout) Prepare repository for $PLATFORM platform!"
cp -rf $PCP_PDI_DIR/$PLATFORM/.??* $PCP_PDI_DIR/    # exist status is ignored for this copy
cp -rf $PCP_PDI_DIR/$PLATFORM/* $PCP_PDI_DIR/
if [ $? -ne 0 ]
then
	echo "HOOK ERROR: (post-checkout) Unable to copy files for $PCP_PDI_DIR! Exiting..."
	exit 1
fi
cp -rf $PCP_DIRECTIO_DIR/$PLATFORM/.??* $PCP_DIRECTIO_DIR/    # exist status is ignored for this copy
cp -rf $PCP_DIRECTIO_DIR/$PLATFORM/* $PCP_DIRECTIO_DIR/
if [ $? -ne 0 ]
then
	echo "HOOK ERROR: (post-checkout) Unable to copy files for $PCP_DIRECTIO_DIR! Exiting..."
	exit 1
fi

cp -rf $AP_PDI_DIR/$PLATFORM/.??* $AP_PDI_DIR/    # exist status is ignored for this copy
cp -rf $AP_PDI_DIR/$PLATFORM/* $AP_PDI_DIR/
if [ $? -ne 0 ]
then
	echo "HOOK ERROR: (post-checkout) Unable to copy files for $AP_PDI_DIR! Exiting..."
	exit 1
fi
# do libCnApi changes
if [ $PLATFORM == "xilinx" ]
then
	cp -rf $LIBCNAPI_DIR/target/microblaze_newlib/.??* $LIBCNAPI_DIR/
fi


# finished!
echo "INFO: (post-checkout) Done..."
exit 0

