#!/bin/bash
#
###############################################################################
# This script creates the bsp files in the current directory.
# 
###############################################################################

INPUT_VARS=$@

echo --- This is create-this-bsp ---
echo input parameters: $INPUT_VARS

BSP_TYPE=hal
BSP_DIR=.
NIOS2_BSP_ARGS="--set hal.sys_clk_timer system_timer_ap --cpu-name ap_cpu --settings settings.bsp"
# --set hal.make.bsp_cflags_debug none

#NIOS2_BSP_ARGS="--set hal.max_file_descriptors 4 --set hal.enable_small_c_library true --set hal.sys_clk_timer none --set hal.timestamp_timer none --set hal.enable_exit false --set hal.enable_c_plus_plus false --set hal.enable_lightweight_device_driver_api true --set hal.enable_clean_exit false --set hal.enable_sim_optimize false --set hal.enable_reduced_device_drivers true  --set hal.make.bsp_cflags_optimization '-Os'"

# process arguments
SKIP_MAKE=
NO_OPT=
while [ $# -gt 0 ]
do
  case "$1" in
      # Don't run make if create-this-app script is called with --no-make arg
      --no-make)
          SKIP_MAKE=1
          ;;
      --rebuild)
          rm -f ./public.mk ./settings.bsp
          ;;
      --debug)
          NO_OPT=1
          ;;
	  --sopcdir)
		 shift
		 SOPC_DIR=../$1
		 echo SOPC_DIR set to \"$SOPC_DIR\"
		 echo -------------------------------
		 ;;
      *)
          NIOS2_BSP_ARGS="$NIOS2_BSP_ARGS $1"
          ;;
  esac
  shift
done

if [ -z "$SOPC_DIR" ]; then
echo "No SOPC directory specified !"
echo "Use parameter: --sopcdir <SOPC_directory>"
exit 1
fi

if [ -z "$NO_OPT" ]; then
    NIOS2_BSP_ARGS="${NIOS2_BSP_ARGS} --set hal.make.bsp_cflags_optimization -O2"
else
    NIOS2_BSP_ARGS="${NIOS2_BSP_ARGS} --set hal.make.bsp_cflags_optimization -O2" # for deuggig also at O2 for now.	
fi

# Run nios2-bsp utility to create a hal BSP in this directory
# for the system with a .sopc file in $SOPC_DIR.
cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR $NIOS2_BSP_ARGS"

echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}
if [ -z "$SKIP_MAKE" ]; then
	echo "create-this-bsp: Running make"
	make
fi
