# TCL File Generated by Component Editor 9.1sp2
# Tue Jun 29 14:00:13 CEST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | cnApi_Av2Av "CN Api Interface (Avalon2Avalon)" v1.0
# | Joerg Zelenka (B&R) 2010.06.29.14:00:13
# | Avalon to Avalon Process Data Interface
# | 
# | C:/vhdl/altera/DBC3C40/DPR_testprj/EPL/cnApi_Av2Av.vhd
# | 
# |    ./cnApi_Av2Av.vhd syn, sim
# |    ./cnApi_Av2Av_DPR.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module cnApi_Av2Av
# | 
set_module_property DESCRIPTION "Avalon to Avalon Process Data Interface"
set_module_property NAME cnApi_Av2Av
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "POWERLINK/PDI"
set_module_property AUTHOR "Joerg Zelenka (B&R)"
set_module_property DISPLAY_NAME "CN Api Interface (Avalon2Avalon)"
set_module_property TOP_LEVEL_HDL_FILE cnApi_Av2Av.vhd
set_module_property TOP_LEVEL_HDL_MODULE cnApi_Av2Av
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file cnApi_Av2Av.vhd {SYNTHESIS SIMULATION}
add_file cnApi_Av2Av_DPR.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter bUseTripleBuffer BOOLEAN true ""
set_parameter_property bUseTripleBuffer DEFAULT_VALUE true
set_parameter_property bUseTripleBuffer DISPLAY_NAME bUseTripleBuffer
set_parameter_property bUseTripleBuffer ENABLED false
set_parameter_property bUseTripleBuffer UNITS None
set_parameter_property bUseTripleBuffer DESCRIPTION ""
set_parameter_property bUseTripleBuffer DISPLAY_HINT ""
set_parameter_property bUseTripleBuffer AFFECTS_GENERATION false
set_parameter_property bUseTripleBuffer HDL_PARAMETER true
add_parameter iTpdoBufSize_g INTEGER 100 byte
set_parameter_property iTpdoBufSize_g DEFAULT_VALUE 100
set_parameter_property iTpdoBufSize_g DISPLAY_NAME iTpdoBufSize_g
set_parameter_property iTpdoBufSize_g UNITS None
set_parameter_property iTpdoBufSize_g ALLOWED_RANGES 0:1500
set_parameter_property iTpdoBufSize_g DESCRIPTION byte
set_parameter_property iTpdoBufSize_g DISPLAY_HINT ""
set_parameter_property iTpdoBufSize_g AFFECTS_GENERATION false
set_parameter_property iTpdoBufSize_g HDL_PARAMETER true
add_parameter iRpdoBufSize_g INTEGER 100 byte
set_parameter_property iRpdoBufSize_g DEFAULT_VALUE 100
set_parameter_property iRpdoBufSize_g DISPLAY_NAME iRpdoBufSize_g
set_parameter_property iRpdoBufSize_g UNITS None
set_parameter_property iRpdoBufSize_g ALLOWED_RANGES 0:1500
set_parameter_property iRpdoBufSize_g DESCRIPTION byte
set_parameter_property iRpdoBufSize_g DISPLAY_HINT ""
set_parameter_property iRpdoBufSize_g AFFECTS_GENERATION false
set_parameter_property iRpdoBufSize_g HDL_PARAMETER true
add_parameter iTpdoObjNumber_g INTEGER 10 objects
set_parameter_property iTpdoObjNumber_g DEFAULT_VALUE 10
set_parameter_property iTpdoObjNumber_g DISPLAY_NAME iTpdoObjNumber_g
set_parameter_property iTpdoObjNumber_g UNITS None
set_parameter_property iTpdoObjNumber_g ALLOWED_RANGES 0:1500
set_parameter_property iTpdoObjNumber_g DESCRIPTION objects
set_parameter_property iTpdoObjNumber_g DISPLAY_HINT ""
set_parameter_property iTpdoObjNumber_g AFFECTS_GENERATION false
set_parameter_property iTpdoObjNumber_g HDL_PARAMETER true
add_parameter iRpdoObjNumber_g INTEGER 10 objects
set_parameter_property iRpdoObjNumber_g DEFAULT_VALUE 10
set_parameter_property iRpdoObjNumber_g DISPLAY_NAME iRpdoObjNumber_g
set_parameter_property iRpdoObjNumber_g UNITS None
set_parameter_property iRpdoObjNumber_g ALLOWED_RANGES 0:1500
set_parameter_property iRpdoObjNumber_g DESCRIPTION objects
set_parameter_property iRpdoObjNumber_g DISPLAY_HINT ""
set_parameter_property iRpdoObjNumber_g AFFECTS_GENERATION false
set_parameter_property iRpdoObjNumber_g HDL_PARAMETER true
add_parameter iAsyTxBufSize_g INTEGER 1500 byte
set_parameter_property iAsyTxBufSize_g DEFAULT_VALUE 1500
set_parameter_property iAsyTxBufSize_g DISPLAY_NAME iAsyTxBufSize_g
set_parameter_property iAsyTxBufSize_g UNITS None
set_parameter_property iAsyTxBufSize_g ALLOWED_RANGES 0:1500
set_parameter_property iAsyTxBufSize_g DESCRIPTION byte
set_parameter_property iAsyTxBufSize_g DISPLAY_HINT ""
set_parameter_property iAsyTxBufSize_g AFFECTS_GENERATION false
set_parameter_property iAsyTxBufSize_g HDL_PARAMETER true
add_parameter iAsyRxBufSize_g INTEGER 1500 byte
set_parameter_property iAsyRxBufSize_g DEFAULT_VALUE 1500
set_parameter_property iAsyRxBufSize_g DISPLAY_NAME iAsyRxBufSize_g
set_parameter_property iAsyRxBufSize_g UNITS None
set_parameter_property iAsyRxBufSize_g ALLOWED_RANGES 0:1500
set_parameter_property iAsyRxBufSize_g DESCRIPTION byte
set_parameter_property iAsyRxBufSize_g DISPLAY_HINT ""
set_parameter_property iAsyRxBufSize_g AFFECTS_GENERATION false
set_parameter_property iAsyRxBufSize_g HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pcp
# | 
add_interface pcp avalon end
set_interface_property pcp addressAlignment DYNAMIC
set_interface_property pcp associatedClock pcp_clk
set_interface_property pcp burstOnBurstBoundariesOnly false
set_interface_property pcp explicitAddressSpan 0
set_interface_property pcp holdTime 0
set_interface_property pcp isMemoryDevice false
set_interface_property pcp isNonVolatileStorage false
set_interface_property pcp linewrapBursts false
set_interface_property pcp maximumPendingReadTransactions 0
set_interface_property pcp printableDevice false
set_interface_property pcp readLatency 0
set_interface_property pcp readWaitStates 2
set_interface_property pcp readWaitTime 2
set_interface_property pcp setupTime 0
set_interface_property pcp timingUnits Cycles
set_interface_property pcp writeWaitTime 0

set_interface_property pcp ASSOCIATED_CLOCK pcp_clk
set_interface_property pcp ENABLED true

add_interface_port pcp pcp_chipselect chipselect Input 1
add_interface_port pcp pcp_address address Input 15
add_interface_port pcp pcp_writedata writedata Input 32
add_interface_port pcp pcp_readdata readdata Output 32
add_interface_port pcp pcp_read read Input 1
add_interface_port pcp pcp_write write Input 1
add_interface_port pcp pcp_byteenable byteenable Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ap
# | 
add_interface ap avalon end
set_interface_property ap addressAlignment DYNAMIC
set_interface_property ap associatedClock ap_clk
set_interface_property ap burstOnBurstBoundariesOnly false
set_interface_property ap explicitAddressSpan 0
set_interface_property ap holdTime 0
set_interface_property ap isMemoryDevice false
set_interface_property ap isNonVolatileStorage false
set_interface_property ap linewrapBursts false
set_interface_property ap maximumPendingReadTransactions 0
set_interface_property ap printableDevice false
set_interface_property ap readLatency 0
set_interface_property ap readWaitStates 2
set_interface_property ap readWaitTime 2
set_interface_property ap setupTime 0
set_interface_property ap timingUnits Cycles
set_interface_property ap writeWaitTime 0

set_interface_property ap ASSOCIATED_CLOCK ap_clk
set_interface_property ap ENABLED true

add_interface_port ap ap_chipselect chipselect Input 1
add_interface_port ap ap_address address Input 15
add_interface_port ap ap_writedata writedata Input 32
add_interface_port ap ap_readdata readdata Output 32
add_interface_port ap ap_read read Input 1
add_interface_port ap ap_write write Input 1
add_interface_port ap ap_byteenable byteenable Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pcp_clk
# | 
add_interface pcp_clk clock end

set_interface_property pcp_clk ENABLED true

add_interface_port pcp_clk pcp_Clk clk Input 1
add_interface_port pcp_clk pcp_Reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ap_clk
# | 
add_interface ap_clk clock end

set_interface_property ap_clk ENABLED true

add_interface_port ap_clk ap_Clk clk Input 1
add_interface_port ap_clk ap_Reset reset Input 1
# | 
# +-----------------------------------
