#!/bin/bash
#
###############################################################################
# This script creates the bsp files in the current directory.
# 
###############################################################################

INPUT_VARS=$@

echo --- This is create-this-bsp ---
echo input parameters: $INPUT_VARS

BSP_TYPE=hal
BSP_DIR=.
NIOS2_BSP_ARGS="--set hal.sys_clk_timer system_timer"
# --set hal.make.bsp_cflags_debug none

#NIOS2_BSP_ARGS="--set hal.max_file_descriptors 4 --set hal.enable_small_c_library true --set hal.sys_clk_timer none --set hal.timestamp_timer none --set hal.enable_exit false --set hal.enable_c_plus_plus false --set hal.enable_lightweight_device_driver_api true --set hal.enable_clean_exit false --set hal.enable_sim_optimize false --set hal.enable_reduced_device_drivers true  --set hal.make.bsp_cflags_optimization '-Os'"

# process arguments
SKIP_MAKE=
NO_OPT=
while [ $# -gt 0 ]
do
  case "$1" in
      # Don't run make if create-this-app script is called with --no-make arg
      --no-make)
          SKIP_MAKE=1
          ;;
      --rebuild)
		  if [ -f makefile ]; then
		  make clean
		  fi
		  rm -f ./public.mk ./settings.bsp
          ;;
      --debug)
          NO_OPT=1
          ;;
      --debug_lvl)
         shift
         # argument currently not used
         ;;  
	  --sopcdir)
		 shift
		 SOPC_DIR=../$1
		 echo SOPC_DIR set to \"$SOPC_DIR\"
		 echo -------------------------------
		 ;;
      *)
          NIOS2_BSP_ARGS="$NIOS2_BSP_ARGS $1"
          ;;
  esac
  shift
done

if [ -z "$SOPC_DIR" ]; then
echo "No SOPC directory specified !"
echo "Use parameter: --sopcdir <SOPC_directory>"
exit 1
fi

if [ -z "$NO_OPT" ]; then
    NIOS2_BSP_ARGS="${NIOS2_BSP_ARGS} --set hal.make.bsp_cflags_optimization -O3"
else
    NIOS2_BSP_ARGS="${NIOS2_BSP_ARGS} --set hal.make.bsp_cflags_optimization -O1" # for debugging
fi

# Run nios2-bsp utility to create a hal BSP in this directory
# for the system with a .sopc file in $SOPC_DIR.
cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR $NIOS2_BSP_ARGS"

echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}

# --- Workaround to copy modified src files manually           ---
# --- in case they are not recognized by the tcl file adaption ---
CURPATH=$PWD
MOD_DRIVER_PATH=${CURPATH}/../../../fpga/altera/driver

if [ ! -d ${MOD_DRIVER_PATH} ]; then
  echo "Error: ${MOD_DRIVER_PATH} not present!"
  exit 1
fi

echo ""
echo "INFO: Replacing modified altera drivers for BSP manually (Workaround)"

cp -p -f -v $MOD_DRIVER_PATH/altera_avalon_epcs_flash_controller/HAL/inc/*.h \
            $CURPATH/drivers/inc 
cp -p -f -v $MOD_DRIVER_PATH/altera_avalon_epcs_flash_controller/HAL/src/*.c \
            $CURPATH/drivers/src 
# --- End of workaround ---

if [ -z "$SKIP_MAKE" ]; then
	echo "create-this-bsp: Running make"
	make
fi
