
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver parameters
*
*******************************************************************/

#ifndef _CNAPICFG_H_
#define _CNAPICFG_H_

/* Definitions for peripheral AXI_POWERLINK_0 */
#define CN_API_INT_AXI
#define AP_IS_LITTLE_ENDIAN
#define AP_USES_AXI_BUS
#define PCP_PDI_RPDO_CHANNELS 3
#define PCP_PDI_TPDO_CHANNELS 1
#define PCP_PDI_REVISION 2
#define PCP_FPGA_SYSID_ID 0u
#define PCP_FPGA_TIMESYNCHW 1
#define PCP_PDI_ASYNC_BUF_MAX 2

#endif /* _CNAPICFG_H_ */

/******************************************************************/

