# TCL File Generated by Component Editor 10.0sp1
# Fri Sep 10 14:13:38 CEST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_master_bridge "Avalon Memory Mapped Master Bridge" v1.0
# | Joerg Zelenka (B&R 2010) 2010.09.10.14:13:38
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalon_master_bridge
# | 
set_module_property NAME avalon_master_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property AUTHOR "Joerg Zelenka (B&R 2010)"
set_module_property DISPLAY_NAME "Avalon Memory Mapped Master Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point AvalonMaster
# | 
add_interface AvalonMaster avalon start
set_interface_property AvalonMaster associatedClock clock
set_interface_property AvalonMaster burstOnBurstBoundariesOnly false
set_interface_property AvalonMaster doStreamReads false
set_interface_property AvalonMaster doStreamWrites false
set_interface_property AvalonMaster linewrapBursts false

set_interface_property AvalonMaster ASSOCIATED_CLOCK clock
set_interface_property AvalonMaster ENABLED true

add_interface_port AvalonMaster avalon_address address Output 15
add_interface_port AvalonMaster avalon_read read Output 1
add_interface_port AvalonMaster avalon_waitrequest waitrequest Input 1
add_interface_port AvalonMaster avalon_readdata readdata Input 32
add_interface_port AvalonMaster avalon_write write Output 1
add_interface_port AvalonMaster avalon_writedata writedata Output 32
add_interface_port AvalonMaster avalon_readdatavalid readdatavalid Input 1
add_interface_port AvalonMaster avalon_byteenable byteenable Output 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
add_interface_port clock reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq0
# | 
add_interface irq0 interrupt start
set_interface_property irq0 associatedAddressablePoint AvalonMaster
set_interface_property irq0 associatedClock clock
set_interface_property irq0 irqScheme INDIVIDUAL_REQUESTS

set_interface_property irq0 ASSOCIATED_CLOCK clock
set_interface_property irq0 ENABLED true

add_interface_port irq0 ap_irq irq Input 1
# | 
# +-----------------------------------
